PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "app_author" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "bio" varchar(255) NULL, "updated_at" datetime NOT NULL, "created_at" datetime NOT NULL, "user_id" bigint NOT NULL UNIQUE REFERENCES "app_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO app_author VALUES(1,'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.','1/1/2025','11/18/2024',1);
INSERT INTO app_author VALUES(2,'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.','1/1/2025','10/5/2024',2);
INSERT INTO app_author VALUES(3,'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.','1/1/2025','8/19/2024',3);
INSERT INTO app_author VALUES(4,'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.','1/1/2025','10/29/2024',4);
INSERT INTO app_author VALUES(5,'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.','1/1/2025','10/18/2024',5);
INSERT INTO app_author VALUES(6,'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.','1/1/2025','6/21/2024',6);
INSERT INTO app_author VALUES(7,'In congue. Etiam justo.','1/1/2025','10/29/2024',7);
INSERT INTO app_author VALUES(8,'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','1/1/2025','10/20/2024',8);
INSERT INTO app_author VALUES(9,'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.','1/1/2025','6/17/2024',9);
INSERT INTO app_author VALUES(10,'In sagittis dui vel nisl. Duis ac nibh.','1/1/2025','7/9/2024',10);
INSERT INTO app_author VALUES(11,'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.','1/1/2025','12/19/2024',11);
INSERT INTO app_author VALUES(12,'Integer ac leo.','1/1/2025','9/17/2024',12);
INSERT INTO app_author VALUES(13,'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.','1/1/2025','9/12/2024',13);
INSERT INTO app_author VALUES(14,'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.','1/1/2025','7/26/2024',14);
INSERT INTO app_author VALUES(15,'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.','1/1/2025','11/23/2024',15);
INSERT INTO app_author VALUES(16,'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.','1/1/2025','9/26/2024',16);
INSERT INTO app_author VALUES(17,'Maecenas rhoncus aliquam lacus.','1/1/2025','6/4/2024',17);
INSERT INTO app_author VALUES(18,'Phasellus sit amet erat.','1/1/2025','9/4/2024',18);
INSERT INTO app_author VALUES(19,'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.','1/1/2025','11/28/2024',19);
INSERT INTO app_author VALUES(20,'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.','1/1/2025','10/13/2024',20);
COMMIT;
