# Generated by Django 5.2.1 on 2025-06-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_is_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auther',
            new_name='Author',
        ),
    ]
